baseURL = 'https://jgk-im.pages.dev/'
languageCode = 'ko-kr'
title = '김종격의 게임 블로그'
theme = 'clarity'

DefaultContentLanguage = 'en'

[taxonomies]
category = 'categories'
tag = 'tags'
series = 'series'

[outputs]
home = ["HTML", "RSS", "JSON"]