
# socials
twitter = '@jgk_im'
largeTwitterCard = false
introDescription = "게임과 그에 관련된 것들을 리뷰합니다."
introURL = false # "about/" 이후 about에 추가 가능
# description = "test" # <meta name = "desctiption" content="<여기 들어갈 것>"> site meta tag (SEO) 입력하기
# keywords = ["game", "review", "blog"]

# showShare = false

# google analytics id
ga_analytics = ""

# google tag manager
google_tag_manager_id = ""

# limit the number of txonomies links shown on the sidebar of each page by default.
numberOfTagsShown = 15

imagesDir = "images/"
iconsDir = "icons/"
fontsDir = "fonts/"

logo = "logo.png"
footerLogo = "logo.png"

mainSections = ["posts"]

mobileNavigation = "right"
pinFeatured = true
since = 2024

[author]
name = "김종격"
