[[main]]
name = "Home"
url = ""
weight = -110

[[main]]
name = "Review"
url = "review"
weight = -100

[[social]]
name = "twitter"
type = "social"
weight = 1
url = "https://twitter.com/jgk_im"